services:
  api:
    container_name: api
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    volumes:
      - ./src/:/app/src
    command: yarn dev
