services:
  api:
    container_name: api
    restart: always
    build: .
    env_file:
      - .docker.env
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: yarn dev

volumes:
  node_modules:
